//
// ArticleContributor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ArticleContributor: Codable {

    public var articleId: UUID?
    public var article: Article?
    public var contributorId: UUID?
    public var contributor: Contributor?
    public var type: ContributionType?
    public var filter: String?
    public var order: Int?

    public init(articleId: UUID? = nil, article: Article? = nil, contributorId: UUID? = nil, contributor: Contributor? = nil, type: ContributionType? = nil, filter: String? = nil, order: Int? = nil) {
        self.articleId = articleId
        self.article = article
        self.contributorId = contributorId
        self.contributor = contributor
        self.type = type
        self.filter = filter
        self.order = order
    }

}

