//
// ArticleTagsModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ArticleTagsModel: Codable {

    public var items: [ArticleTagItemModel]?
    public var metaData: PagedListMetaData?

    public init(items: [ArticleTagItemModel]? = nil, metaData: PagedListMetaData? = nil) {
        self.items = items
        self.metaData = metaData
    }

}

