//
// AuditableEntity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuditableEntity: Codable {

    public var createdBy: UUID?
    public var updatedBy: UUID?
    public var deletedBy: UUID?
    public var createdDate: Date?
    public var updatedDate: Date?
    public var deletedDate: Date?
    public var isHidden: Bool?
    public var isDeleted: Bool?

    public init(createdBy: UUID? = nil, updatedBy: UUID? = nil, deletedBy: UUID? = nil, createdDate: Date? = nil, updatedDate: Date? = nil, deletedDate: Date? = nil, isHidden: Bool? = nil, isDeleted: Bool? = nil) {
        self.createdBy = createdBy
        self.updatedBy = updatedBy
        self.deletedBy = deletedBy
        self.createdDate = createdDate
        self.updatedDate = updatedDate
        self.deletedDate = deletedDate
        self.isHidden = isHidden
        self.isDeleted = isDeleted
    }

}

