//
// AzureSearchServiceAutocompleteModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AzureSearchServiceAutocompleteModel: Codable {

    public var values: [String]?

    public init(values: [String]? = nil) {
        self.values = values
    }

}
