//
// CommunicationUserTokenModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CommunicationUserTokenModel: Codable {

    public var token: String?
    public var expiresOn: Date?
    public var communicationUserId: String?
    public var gatewary: String?

    public init(token: String? = nil, expiresOn: Date? = nil, communicationUserId: String? = nil, gatewary: String? = nil) {
        self.token = token
        self.expiresOn = expiresOn
        self.communicationUserId = communicationUserId
        self.gatewary = gatewary
    }

}

