//
// ConsultationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ConsultationType: String, Codable, CaseIterable {
    case hospital = "Hospital"
    case doctor = "Doctor"
    case deal = "Deal"
}
