//
// ContributionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum ContributionType: String, Codable, CaseIterable {
    case reviewedBy = "ReviewedBy"
    case writtenBy = "WrittenBy"
    case interviewWith = "InterviewWith"
}
