//
// CreateEquipmentCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateEquipmentCommand: Codable {

    public var name: String?
    public var description: String?
    public var medias: [MediaViewModel]?
    public var auditableEntity: AuditableEntity?

    public init(name: String? = nil, description: String? = nil, medias: [MediaViewModel]? = nil, auditableEntity: AuditableEntity? = nil) {
        self.name = name
        self.description = description
        self.medias = medias
        self.auditableEntity = auditableEntity
    }

}

