//
// CreateChatUserCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateChatUserCommand: Codable {

    public var nickname: String?
    public var profileUrl: String?
    public var issueAccessToken: Bool?
    public var discoveryKeys: [String]?
    public var hospitalId: UUID?

    public init(nickname: String? = nil, profileUrl: String? = nil, issueAccessToken: Bool? = nil, discoveryKeys: [String]? = nil, hospitalId: UUID? = nil) {
        self.nickname = nickname
        self.profileUrl = profileUrl
        self.issueAccessToken = issueAccessToken
        self.discoveryKeys = discoveryKeys
        self.hospitalId = hospitalId
    }

}

