//
// DealPackage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DealPackage: Codable {

    public var id: UUID?
    public var dealId: UUID?
    public var deal: Deal?
    public var refundPolicy: RefundPolicy?
    public var additionalServices: String?
    public var accomodation: String?
    public var transfer: String?
    public var bonus: String?
    public var price: Double?
    public var managers: [Manager]?
    public var questions: [Question]?
    public var bookings: [Booking]?
    public var auditableEntity: AuditableEntity?

    public init(id: UUID? = nil, dealId: UUID? = nil, deal: Deal? = nil, refundPolicy: RefundPolicy? = nil, additionalServices: String? = nil, accomodation: String? = nil, transfer: String? = nil, bonus: String? = nil, price: Double? = nil, managers: [Manager]? = nil, questions: [Question]? = nil, bookings: [Booking]? = nil, auditableEntity: AuditableEntity? = nil) {
        self.id = id
        self.dealId = dealId
        self.deal = deal
        self.refundPolicy = refundPolicy
        self.additionalServices = additionalServices
        self.accomodation = accomodation
        self.transfer = transfer
        self.bonus = bonus
        self.price = price
        self.managers = managers
        self.questions = questions
        self.bookings = bookings
        self.auditableEntity = auditableEntity
    }

}

