//
// DealSearchViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DealSearchViewModel: Codable {

    public var id: String?
    public var name: String?
    public var slug: String?
    public var description: String?
    public var marketingType: Int?
    public var photo: String?
    public var photoThumbnail: String?
    public var hospital: HospitalSearchItemViewModel?
    public var packages: [DealPackageSearchViewModel]?

    public init(id: String? = nil, name: String? = nil, slug: String? = nil, description: String? = nil, marketingType: Int? = nil, photo: String? = nil, photoThumbnail: String? = nil, hospital: HospitalSearchItemViewModel? = nil, packages: [DealPackageSearchViewModel]? = nil) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.marketingType = marketingType
        self.photo = photo
        self.photoThumbnail = photoThumbnail
        self.hospital = hospital
        self.packages = packages
    }

}

