//
// DeviceLogin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DeviceLogin: Codable {

    public var id: UUID?
    public var deviceId: UUID?
    public var device: Device?
    public var version: String?
    public var location: Location?
    public var auditableEntity: AuditableEntity?

    public init(id: UUID? = nil, deviceId: UUID? = nil, device: Device? = nil, version: String? = nil, location: Location? = nil, auditableEntity: AuditableEntity? = nil) {
        self.id = id
        self.deviceId = deviceId
        self.device = device
        self.version = version
        self.location = location
        self.auditableEntity = auditableEntity
    }

}

