//
// DoctorCertificatesViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DoctorCertificatesViewModel: Codable {

    public var items: [DoctorCertificateItemViewModel]?
    public var metaData: PagedListMetaData?

    public init(items: [DoctorCertificateItemViewModel]? = nil, metaData: PagedListMetaData? = nil) {
        self.items = items
        self.metaData = metaData
    }

}

