//
// FaqCategoriesViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FaqCategoriesViewModel: Codable {

    public var items: [FaqCategoryItemViewModel]?
    public var metaData: PagedListMetaData?

    public init(items: [FaqCategoryItemViewModel]? = nil, metaData: PagedListMetaData? = nil) {
        self.items = items
        self.metaData = metaData
    }

}

