//
// HospitalSearchItemViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HospitalSearchItemViewModel: Codable {

    public var id: String?
    public var name: String?
    public var slug: String?
    public var description: String?
    public var logo: String?
    public var overview: String?
    public var bedsCount: Int?
    public var operationsPerYear: Int?
    public var foundationYear: Int?
    public var medicalStaffCount: Int?
    public var doctorCount: Int?
    public var countryId: String?
    public var countryName: String?
    public var marketingType: Int?
    public var latitude: Double?
    public var longitude: Double?
    public var country: String?
    public var state: String?
    public var county: String?
    public var city: String?
    public var zipCode: String?
    public var address: String?
    public var medias: [MediaSearchViewModel]?
    public var consultationEnabled: Bool?
    public var consultationFee: Double?
    public var specialtiesSummerized: String?

    public init(id: String? = nil, name: String? = nil, slug: String? = nil, description: String? = nil, logo: String? = nil, overview: String? = nil, bedsCount: Int? = nil, operationsPerYear: Int? = nil, foundationYear: Int? = nil, medicalStaffCount: Int? = nil, doctorCount: Int? = nil, countryId: String? = nil, countryName: String? = nil, marketingType: Int? = nil, latitude: Double? = nil, longitude: Double? = nil, country: String? = nil, state: String? = nil, county: String? = nil, city: String? = nil, zipCode: String? = nil, address: String? = nil, medias: [MediaSearchViewModel]? = nil, consultationEnabled: Bool? = nil, consultationFee: Double? = nil, specialtiesSummerized: String? = nil) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.logo = logo
        self.overview = overview
        self.bedsCount = bedsCount
        self.operationsPerYear = operationsPerYear
        self.foundationYear = foundationYear
        self.medicalStaffCount = medicalStaffCount
        self.doctorCount = doctorCount
        self.countryId = countryId
        self.countryName = countryName
        self.marketingType = marketingType
        self.latitude = latitude
        self.longitude = longitude
        self.country = country
        self.state = state
        self.county = county
        self.city = city
        self.zipCode = zipCode
        self.address = address
        self.medias = medias
        self.consultationEnabled = consultationEnabled
        self.consultationFee = consultationFee
        self.specialtiesSummerized = specialtiesSummerized
    }

}

