//
// HospitalEvaluationItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HospitalEvaluationItemModel: Codable {

    public var name: String?
    public var stars: Int?

    public init(name: String? = nil, stars: Int? = nil) {
        self.name = name
        self.stars = stars
    }

}

