//
// HospitalServicesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HospitalServicesModel: Codable {

    public var items: [HospitalServiceItemModel]?
    public var metaData: PagedListMetaData?

    public init(items: [HospitalServiceItemModel]? = nil, metaData: PagedListMetaData? = nil) {
        self.items = items
        self.metaData = metaData
    }

}

