//
// HospitalModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HospitalModel: Codable {

    public var id: UUID?
    public var languageCode: String?
    public var name: String?
    public var slug: String?
    public var confirmed: Bool?
    public var logo: String?
    public var marketingType: MarketingType?
    public var consultationEnabled: Bool?
    public var consultationFee: Double?
    public var timeZone: String?
    public var websiteUrl: String?
    public var paymentEnabled: Bool?
    public var countryId: UUID?
    public var specialtiesSummerized: String?
    public var accreditations: [HospitalAccreditationItemModel]?
    public var medias: [MediaModel]?
    public var location: LocationModel?
    public var description: String?
    public var overview: String?
    public var content: String?
    public var localizedUrls: [LocalizedUrlModel]?
    public var bedsCount: Int?
    public var operationsPerYear: Int?
    public var foundationYear: Int?
    public var medicalStaffCount: Int?
    public var doctorCount: Int?
    public var contactTel: String?
    public var contactEmail: String?
    public var customStyle: String?
    public var evaluations: [HospitalEvaluationItemModel]?
    public var hospitalWorkingDays: [WorkingDay]?
    public var hospitalSnsHandles: [SnsHandle]?
    public var languages: [HospitalLanguageItemModel]?
    public var awards: [AwardModel]?

    public init(id: UUID? = nil, languageCode: String? = nil, name: String? = nil, slug: String? = nil, confirmed: Bool? = nil, logo: String? = nil, marketingType: MarketingType? = nil, consultationEnabled: Bool? = nil, consultationFee: Double? = nil, timeZone: String? = nil, websiteUrl: String? = nil, paymentEnabled: Bool? = nil, countryId: UUID? = nil, specialtiesSummerized: String? = nil, accreditations: [HospitalAccreditationItemModel]? = nil, medias: [MediaModel]? = nil, location: LocationModel? = nil, description: String? = nil, overview: String? = nil, content: String? = nil, localizedUrls: [LocalizedUrlModel]? = nil, bedsCount: Int? = nil, operationsPerYear: Int? = nil, foundationYear: Int? = nil, medicalStaffCount: Int? = nil, doctorCount: Int? = nil, contactTel: String? = nil, contactEmail: String? = nil, customStyle: String? = nil, evaluations: [HospitalEvaluationItemModel]? = nil, hospitalWorkingDays: [WorkingDay]? = nil, hospitalSnsHandles: [SnsHandle]? = nil, languages: [HospitalLanguageItemModel]? = nil, awards: [AwardModel]? = nil) {
        self.id = id
        self.languageCode = languageCode
        self.name = name
        self.slug = slug
        self.confirmed = confirmed
        self.logo = logo
        self.marketingType = marketingType
        self.consultationEnabled = consultationEnabled
        self.consultationFee = consultationFee
        self.timeZone = timeZone
        self.websiteUrl = websiteUrl
        self.paymentEnabled = paymentEnabled
        self.countryId = countryId
        self.specialtiesSummerized = specialtiesSummerized
        self.accreditations = accreditations
        self.medias = medias
        self.location = location
        self.description = description
        self.overview = overview
        self.content = content
        self.localizedUrls = localizedUrls
        self.bedsCount = bedsCount
        self.operationsPerYear = operationsPerYear
        self.foundationYear = foundationYear
        self.medicalStaffCount = medicalStaffCount
        self.doctorCount = doctorCount
        self.contactTel = contactTel
        self.contactEmail = contactEmail
        self.customStyle = customStyle
        self.evaluations = evaluations
        self.hospitalWorkingDays = hospitalWorkingDays
        self.hospitalSnsHandles = hospitalSnsHandles
        self.languages = languages
        self.awards = awards
    }

}

