//
// HospitalReview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HospitalReview: Codable {

    public var patientId: UUID?
    public var patient: Patient?
    public var hospitalId: UUID?
    public var hospital: Hospital?
    public var body: String?
    public var recommended: Bool?
    public var reviewCategory: ReviewCategory?
    public var rate: Int?

    public init(patientId: UUID? = nil, patient: Patient? = nil, hospitalId: UUID? = nil, hospital: Hospital? = nil, body: String? = nil, recommended: Bool? = nil, reviewCategory: ReviewCategory? = nil, rate: Int? = nil) {
        self.patientId = patientId
        self.patient = patient
        self.hospitalId = hospitalId
        self.hospital = hospital
        self.body = body
        self.recommended = recommended
        self.reviewCategory = reviewCategory
        self.rate = rate
    }

}

