//
// PlansViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PlansViewModel: Codable {

    public var items: [PlanItemViewModel]?
    public var metaData: PagedListMetaData?

    public init(items: [PlanItemViewModel]? = nil, metaData: PagedListMetaData? = nil) {
        self.items = items
        self.metaData = metaData
    }

}

