//
// Procedure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Procedure: String, Codable, CaseIterable {
    case treatment = "Treatment"
    case diagnostic = "Diagnostic"
}
