//
// QuestionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum QuestionStatus: String, Codable, CaseIterable {
    case new = "New"
    case answered = "Answered"
    case replied = "Replied"
    case archived = "Archived"
}
