//
// RefundPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RefundPolicy: String, Codable, CaseIterable {
    case nonRefundable = "NonRefundable"
    case refundable = "Refundable"
    case partialRefundable = "PartialRefundable"
}
