//
// RejectReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RejectReason: String, Codable, CaseIterable {
    case assessmentNotCompleted = "AssessmentNotCompleted"
    case paymentNotCompleted = "PaymentNotCompleted"
    case scheduleNotAvailable = "ScheduleNotAvailable"
    case otherReason = "OtherReason"
}
