//
// ReviewCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ReviewCategory: String, Codable, CaseIterable {
    case services = "Services"
    case hospitality = "Hospitality"
    case transfer = "Transfer"
    case etc = "Etc"
}
