//
// SnsType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum SnsType: String, Codable, CaseIterable {
    case twitter = "Twitter"
    case facebook = "Facebook"
    case instagram = "Instagram"
    case linkedIn = "LinkedIn"
    case youtube = "Youtube"
    case kakaoTalk = "KakaoTalk"
}
