//
// SortingOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum SortingOrder: String, Codable, CaseIterable {
    case ascending = "Ascending"
    case descending = "Descending"
}
