//
// UpdateHospitalSpecialtySequenceCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UpdateHospitalSpecialtySequenceCommand: Codable {

    public var hospitalSpecialtySequence: [UUID]?

    public init(hospitalSpecialtySequence: [UUID]? = nil) {
        self.hospitalSpecialtySequence = hospitalSpecialtySequence
    }

}

