//
// UserLoginInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserLoginInfo: Codable, JSONEncodable, Hashable {

    public var loginProvider: String?
    public var providerKey: String?
    public var providerDisplayName: String?

    public init(loginProvider: String? = nil, providerKey: String? = nil, providerDisplayName: String? = nil) {
        self.loginProvider = loginProvider
        self.providerKey = providerKey
        self.providerDisplayName = providerDisplayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loginProvider
        case providerKey
        case providerDisplayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(loginProvider, forKey: .loginProvider)
        try container.encodeIfPresent(providerKey, forKey: .providerKey)
        try container.encodeIfPresent(providerDisplayName, forKey: .providerDisplayName)
    }
}

