name: CloudHospitalClient
targets:
  CloudHospitalClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: 1.7.5
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
