name: CloudHospitalClient
targets:
  CloudHospitalClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [CloudHospitalClient]
    info:
      path: ./Info.plist
      version: 2.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
