name: CloudHospitalClient
targets:
  CloudHospitalClient:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [CloudHospitalClient]
    info:
      path: ./Info.plist
      version: 1.6.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: Alamofire
