name: CloudHospitalClient
targets:
  CloudHospitalClient:
    type: framework
    platform: iOS
    deploymentTarget: "15"
    sources: [CloudHospitalClient]
    info:
      path: ./Info.plist
      version: 1.7.2
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
