name: CloudHospitalClient
targets:
  CloudHospitalClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [CloudHospitalClient]
    info:
      path: ./Info.plist
      version: 1.3.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
