//
// ChangeLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChangeLog: Codable, Hashable {

    public var id: UUID?
    public var status: Int?
    public var actorId: UUID?
    public var createdDate: Date?

    public init(id: UUID? = nil, status: Int? = nil, actorId: UUID? = nil, createdDate: Date? = nil) {
        self.id = id
        self.status = status
        self.actorId = actorId
        self.createdDate = createdDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case actorId
        case createdDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(actorId, forKey: .actorId)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
    }
}

