//
// CreateSurveyResponseCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSurveyResponseCommand: Codable, Hashable {

    public var surveyId: UUID?
    public var answers: String?

    public init(surveyId: UUID? = nil, answers: String? = nil) {
        self.surveyId = surveyId
        self.answers = answers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case surveyId
        case answers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(surveyId, forKey: .surveyId)
        try container.encodeIfPresent(answers, forKey: .answers)
    }
}

