//
// HeaderNavigationsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HeaderNavigationsAPI {

    /**
     Get all HeaderNavigationItems
     
     - parameter languageCode: (path)  
     - returns: [HeaderNavigationItemModel]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV2HeadernavigationsLanguageCodeGet(languageCode: String) async throws -> [HeaderNavigationItemModel] {
        let requestBuilder = apiV2HeadernavigationsLanguageCodeGetWithRequestBuilder(languageCode: languageCode)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     Get all HeaderNavigationItems
     - GET /api/v2/headernavigations/{languageCode}
     - parameter languageCode: (path)  
     - returns: RequestBuilder<[HeaderNavigationItemModel]> 
     */
    open class func apiV2HeadernavigationsLanguageCodeGetWithRequestBuilder(languageCode: String) -> RequestBuilder<[HeaderNavigationItemModel]> {
        var localVariablePath = "/api/v2/headernavigations/{languageCode}"
        let languageCodePreEscape = "\(APIHelper.mapValueToPathItem(languageCode))"
        let languageCodePostEscape = languageCodePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{languageCode}", with: languageCodePostEscape, options: .literal, range: nil)
        let localVariableURLString = CloudHospitalClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[HeaderNavigationItemModel]>.Type = CloudHospitalClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
