//
// ImagesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ImagesAPI {

    /**

     - parameter files: (form)  (optional)
     - returns: [MediaModel]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV2ImagesPost(files: [URL]? = nil) async throws -> [MediaModel] {
        let requestBuilder = apiV2ImagesPostWithRequestBuilder(files: files)
        let requestTask = requestBuilder.requestTask
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestBuilder.execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestTask.cancel()
        }
    }

    /**
     - POST /api/v2/images
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter files: (form)  (optional)
     - returns: RequestBuilder<[MediaModel]> 
     */
    open class func apiV2ImagesPostWithRequestBuilder(files: [URL]? = nil) -> RequestBuilder<[MediaModel]> {
        let localVariablePath = "/api/v2/images"
        let localVariableURLString = CloudHospitalClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "files": files?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MediaModel]>.Type = CloudHospitalClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
