# This is a basic workflow to help you get started with Actions

name: deploy_to_cocoapods

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: npm ci
      - name: NPM-Version
        # You may pin to the exact commit or the version.
        # uses: Reedyuk/NPM-Version@9b08a57f534ead28c49f7b57665fe9f6d048ff74
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          # This will be the version you want to set in the package.json file
          version: ${{ github.event.client_payload.message.tag }}
          # The location of the package.json file, defaults to current directory.
          package: ./
      - name: Echo payload
        run: echo ${{ github.event.client_payload.message.tag }}
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@b5dec7ea7647ed6edf307ec828d3aeb6bca69f63
        uses: EndBug/add-and-commit@v5.1.0
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      - run: npm run-script build
  deploy:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Cocoapods
      run: gem install cocoapods
    
    # shortcut version
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.9
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
